### PR TITLE
Renaming CheckboxRightWidget to CheckboxLeftWidget to match class signature

### PR DESCRIPTION
**Pull request by stefanoschalkidis**
### Description of Changes
changed ILeftBodyTouch to IRightBodyTouch

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis Why didn’t you check how your changes work with `MDDialog` examples?

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.dialog import MDDialog
from kivymd.uix.list import OneLineAvatarIconListItem

KV = '''
<ItemConfirm>
    on_release: root.set_icon(check)

    CheckboxRightWidget:
        id: check
        group: "check"


FloatLayout:

    MDFlatButton:
        text: "ALERT DIALOG"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_confirmation_dialog()
'''


class ItemConfirm(OneLineAvatarIconListItem):
    divider = None

    def set_icon(self, instance_check):
        instance_check.active = True
        check_list = instance_check.get_widgets(instance_check.group)
        for check in check_list:
            if check != instance_check:
                check.active = False


class Example(MDApp):
    dialog = None

    def build(self):
        return Builder.load_string(KV)

    def show_confirmation_dialog(self):
        if not self.dialog:
            self.dialog = MDDialog(
                title="Phone ringtone",
                type="confirmation",
                items=[
                    ItemConfirm(text="Callisto"),
                    ItemConfirm(text="Luna"),
                    ItemConfirm(text="Night"),
                    ItemConfirm(text="Solo"),
                    ItemConfirm(text="Phobos"),
                    ItemConfirm(text="Diamond"),
                    ItemConfirm(text="Sirena"),
                    ItemConfirm(text="Red music"),
                    ItemConfirm(text="Allergio"),
                    ItemConfirm(text="Magic"),
                    ItemConfirm(text="Tic-tac"),
                ],
                buttons=[
                    MDFlatButton(
                        text="CANCEL", text_color=self.theme_cls.primary_color
                    ),
                    MDFlatButton(
                        text="OK", text_color=self.theme_cls.primary_color
                    ),
                ],
            )
        self.dialog.open()


Example().run()
```

If you propose any changes, first check to see if these changes are displayed correctly in the `Kitchen Sink` app. Next, make the appropriate changes to the documentation.

**Comment by stefanoschalkidis** [comment]
@HeaTTheatR Thanks a lot for your quick reply! In the example you provided, the checkbox appears in the left list container although it's named CheckboxRightWidget. Shouldn't it appear in the right?

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis Yes, there is confusion in the names of the classes.

**Comment by stefanoschalkidis** [comment]
@HeaTTheatR Yes, I agree. I would suggest renaming it then, but either way it will cause issues for programs that rely on the current implementation. What's your opinion?

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis You need to find where the classes with the old name are used and rename them according to the new names.

**Comment by stefanoschalkidis** [comment]
@HeaTTheatR Ok, just to confirm: a PR where all CheckboxRightWidget occurrences are renamed to CheckboxLeftWidget, right?

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis 
Yes.
These files use classes with names `CheckboxRightWidget`:

`kivymd/uix/list.py`
`kivymd/uix/dialog.py`
`demos/kitchen_sink/libs/kv/dialogs.kv`

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis And In doc strings for the `dialog` module.

**Comment by stefanoschalkidis** [comment]
@HeaTTheatR Thanks a lot! I got to go now but I'll do it as soon as I'm back.

**Comment by HeaTTheatR** [comment]
@stefanoschalkidis OK!

**Comment by stefanoschalkidis** [comment]
@HeaTTheatR Ok, I changed the files and tested it locally with `kitchen sink` app. Let me know if anything needs to be changed in addition.

**Pull request merged**
