### PR TITLE
KitchenSink bugfix. Improve and KV profilling.

### PR DESCRIPTION
**Pull request by podraco**
### Description of Changes
1. KV profilling added to kitchen sink demo. for every loaded KV file.
1. Fixed Scrollable area in buttons.kv from the KitchenSink demo. Now the whole screen empty space allows scroll.
1. Added the use of Pathlib.Path for Path Management.
1. Fixed possible bug when loading screens_data.json from outside the working directory.

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@podraco 
Thank you for trying to improve the KivyMD library!
Use one space after the colon:

```
                size_hint_y:None <---------------
	        height:self.minimum_height <---------------
	        cols:3 <---------------
```
Снимок экрана 2020-08-17 в 16 17 59

**Comment by podraco** [comment]
on my way...

**Comment by HeaTTheatR** [comment]
@podraco Separate widgets from each other with one padding.
Снимок экрана 2020-08-17 в 16 34 57

**Review by HeaTTheatR — COMMENTED** [review]
What is the purpose of the `KIVY_PROFILE_LANG` variable?

**Comment by podraco** [comment]
Enables the kivy language profiling, sadly only works with builder.load_file and not builder.load_string

**Comment by ArtemSBulgakov** [comment]
load_string is used to fix utf-8 strings. See "developers" or "license" dialogs from start screen. Not sure how to fix it using load_file.

**Pull request merged**
