### PR TITLE
Replace `Line` in round buttons to `SmoothLine`

### PR DESCRIPTION
**Pull request by Neizvestnyj**
I replaced the standard lines in canvas with smooth lines, so it looks much better.

```python
from kivy.lang import Builder

from kivymd.app import MDApp


KV = '''
MDScreen:

    MDRoundFlatButton:
        text: "MDRoundFlatButton"
        pos_hint: {"center_x": .5, "center_y": .7}
        
    MDRoundFlatIconButton:
        text: "MDRoundFlatIconButton"
        pos_hint: {"center_x": .5, "center_y": .6}
        
'''


class MyApp(MDApp):
    def build(self):
        return Builder.load_string(KV)


MyApp().run()
```

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 
Снимок экрана 2021-08-13 в 21 55 31

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj
> Снимок экрана 2021-08-13 в 21 55 31

hmm

**Comment by Neizvestnyj** [comment]
Looks like kivy bug...

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj
> Снимок экрана 2021-08-13 в 21 55 31

I checked. There are no such bug in Windows/Linux. I dont have OSX(:

**Comment by HeaTTheatR** [comment]
@Neizvestnyj It is displayed crookedly on my computer :(

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj It is displayed crookedly on my computer :(

I will try to find out about this on the `kivy` server

**Pull request closed without merging**
