### PR TITLE
Elevation behavior upgrade.

### PR DESCRIPTION
**Pull request by podraco**
Elevation behavior upgrade.

### Description of Changes
Elevation behavior redesign to comply with the material design spec.
Rotation added to the background behavior and elevation behavior
radius is now a VariableListProperty and can be drawn inside the shadow

### Screenshots

Examples added to the kitchen sink screen.

https://user-images.githubusercontent.com/5509325/107167835-7e8f0f80-697f-11eb-8ad6-909dc2542363.mp4

The screen will unload i'ts contents after 10 seconds outside the elevation screen.

https://user-images.githubusercontent.com/5509325/107167822-733be400-697f-11eb-91c9-f35cb3254fbb.mp4

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@podraco 

Снимок экрана 2021-02-08 в 10 14 49

```
                        MDCard:
                            elevation: 36
                            size_hint: None, None
                            size: "60dp", "60dp"
                            x: 40
                            y: 40
                            radius: 15
```

**Comment by HeaTTheatR** [comment]
@podraco 

Also after merging the changes, the following issue occurred:

Before:

https://user-images.githubusercontent.com/16930280/107211341-7930d400-6a16-11eb-8335-62c9034cc9de.mov

After:

https://user-images.githubusercontent.com/16930280/107211390-88178680-6a16-11eb-8463-6bf57c401227.mov

**Comment by HeaTTheatR** [comment]
@podraco 

The behavior of the `Backdrop` class also slows down:

https://user-images.githubusercontent.com/16930280/107211512-b6956180-6a16-11eb-8fc6-3c85eebfdd09.mov

**Comment by HeaTTheatR** [comment]
@podraco 

The shadow animation also behaves strangely:

https://user-images.githubusercontent.com/16930280/107212449-06c0f380-6a18-11eb-81f1-4549b178dcb4.mov

**Comment by HeaTTheatR** [comment]
@podraco 

The shadow animation also behaves strangely:
ezgif-7-f1413d3cdd9c

**Comment by HeaTTheatR** [comment]
@podraco 

Slows down:

https://user-images.githubusercontent.com/16930280/107213634-cebab000-6a19-11eb-8f3a-63d5119db159.mov

**Comment by HeaTTheatR** [comment]
@podraco 

Снимок экрана 2021-02-08 в 14 29 17

**Comment by HeaTTheatR** [comment]
```python

class CommonElevationBehavior(Widget):
    """Common base class for rectangular and circular elevation behavior."""

    elevation = BoundedNumericProperty(0, min=0)
    """
    Elevation of the widget

    .. note::

        Altho this value does not represent the current elevation of the widget.
        _elevation can be used to animate the current elevation and come back
        using the `elevation` property directly.

        For example:

        .. code-block:: kv

            <Widget_with_shadow>
                on_press:
                    Animation.cancel_all(self)
                    Animation(_elevation = 10, d=1).start(widget)
                on_release:
                    Animation.cancel_all(self)
                    Animation(_elevation = self.elevation).start(self)
```


`Animation.cancel_all(self)` - this will cancel all animation including ripple effect animation.

**Comment by HeaTTheatR** [comment]
> @podraco
> 
> The shadow animation also behaves strangely:
> ezgif-7-f1413d3cdd9c

This can be fixed as follows:

```python
from kivy.lang import Builder
from kivy.uix.behaviors import ButtonBehavior

from kivymd.app import MDApp
from kivymd.uix.behaviors import CircularElevationBehavior, CircularRippleBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
#:import Animation kivy.animation.Animation


MDScreen:

    RectangularRippleButton:
        size_hint: None, None
        size: "50dp", "50dp"
        md_bg_color: .2, .2, .2, 1
        pos_hint: {"center_x": .5, "center_y": .5}
        on_press: Animation(_elevation=40, d=1).start(self)
        on_release: Animation(_elevation=6, d=1).start(self)
'''


class RectangularRippleButton(
    CircularElevationBehavior,
    CircularRippleBehavior,
    ButtonBehavior,
    MDBoxLayout,
):
    def __init__(self, **kv):
        super().__init__(**kv)
        self.elevation = 6

    def on_size(self, *args):
        self.radius = [self.size[0] / 2]


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
@podraco 
At the moment, the animation of the shadow of the button when pressed occurs in the `button` module:

Снимок экрана 2021-02-08 в 15 34 57

**Comment by podraco** [comment]
i believe it must be the drawing instructions, since a larger texture requires a larger amount of time to draw... I'm Testing with threading to generate the textures in a subprocess

**Comment by HeaTTheatR** [comment]
@podraco 
Good. I just showed something that even on a computer slows down noticeably. It simply won't be possible to use it on a mobile device.

**Comment by HeaTTheatR** [comment]
@podraco 
I also worked on minor fixes, but I'm busy with this one right now - https://material.io/design/interaction/selection.html

**Comment by HeaTTheatR** [comment]
@podraco 
Therefore, I cannot join the work on these changes.

**Comment by podraco** [comment]
I found this code inside the base elevation button class, it was calling a lot more times the drawing instruction than required.
```py
def on_elevation(self, instance, value):
    [...]
    self._anim_raised.bind(on_progress=self._do_anim_raised)
    [...]

def _do_anim_raised(self, animation, instance, value):
    self._elevation += value
    if self._elevation < self._elevation_raised + 2:
        self._update_shadow(instance, self._elevation)
```
Each step of a elevation is processed as a frame,. Since textures only allows integers as positions to draw
Also, in the elevation specs, each raised button should have a difference of 6 elevation values between raised and resting state

**Comment by podraco** [comment]
it's understandable, i'm gonna work on a mock up with the old version and let the last classes to be a different class.

**Comment by HeaTTheatR** [comment]
@podraco 
Yes, that's what I mean: the new API requires a different approach to the old methods.

**Comment by HeaTTheatR** [comment]
@podraco 
By the way, you can already submit the expence to the `OpenCollective`:

Снимок экрана 2021-02-08 в 21 26 35

**Comment by podraco** [comment]
https://user-images.githubusercontent.com/5509325/107264681-e2114f80-6a08-11eb-8906-8ef94df6d7ac.mp4

i found something odd, the fps monitor states it never drops below 60 fps

**Comment by podraco** [comment]
> @podraco
> By the way, you can already submit the expence to the `OpenCollective`:
> 
> Снимок экрана 2021-02-08 в 21 26 35

thanks

**Comment by HeaTTheatR** [comment]
@podraco 


> @podraco
> By the way, you can already submit the expence to the `OpenCollective`:
> 
> Снимок экрана 2021-02-08 в 21 26 35

The work turned out to be much more than I could estimate, but, unfortunately, at the moment we have exhausted the entire budget.

**Comment by podraco** [comment]
don't worry, i'll be around for a time being, until i can get a new job or project to work with, until then, i want to be of help, since i use kivymd for most of my local projects.

**Comment by HeaTTheatR** [comment]
@podraco 


https://user-images.githubusercontent.com/16930280/107265270-1e6a9d00-6a55-11eb-80ef-03f9a58ff4ba.mov

FPS - 29

**Comment by podraco** [comment]
Same error, it was requesting a complete draw of the shadow canvas instead of changing the shadow transparency.
```
    update_status(self, *_):
        [...]
        if self.status == "closed":
            self._elevation = 0
            self._update_shadow(self, self._elevation)
        else:
            self._elevation = self.elevation
            self._update_shadow(self, self._elevation)
```

**Comment by podraco** [comment]
#822

**Pull request merged**
