### PR TITLE
Add new demos (Material Studies) and some enhancements

### PR DESCRIPTION
**Pull request by kulothunganug**
### Description of Changes
* Added New [Material Studies Apps](https://material.io/design/material-studies/about-our-material-studies.html#about-material-studies)

1.  [Rally](https://material.io/design/material-studies/rally.html)
rally-pr

2.  [Fortnightly](https://material.io/design/material-studies/fortnightly.html)
fortnightly-pr

* Removed [Shrine](https://material.io/design/material-studies/shrine.html) Demo App (will be added later!)
shrine-pr

### CODE REVIEW

**Comment by ArtemSBulgakov** [comment]
Hi. You made a great work!

It's really helpful for people to see more demos.

Some thoughts. I think it's better to store studies in `demos` directory instead of `demos/studies` and have `README.md` with a link to study for each app.

By the way, why don't you use git from system? It's easier to make changes using IDE and commit by one command.

I'll add WIP label because as I understand you want to return Shrine.

**Comment by kulothunganug** [comment]
@ArtemSBulgakov do u telling something like this to store studies?
```
KivyMD
|__demos
|    |__kitchen_sink
|    |__fortnightly
|    |__rally
|    |__...
|....etc
```
kivymd's shrine has no angled cut design according to [material's shrine](https://material.io/design/material-studies/shrine.html#about-shrine) and also it take's so much of time, i will add it later in another PR

sorry for my english

**Comment by ArtemSBulgakov** [comment]
@Kulothungan16 Yes, I mean that structure.

**Comment by kulothunganug** [comment]
@ArtemSBulgakov it's very easy to use git in terminal
Thank you for your advice! :pray:

**Comment by kulothunganug** [comment]
@ArtemSBulgakov i had completed your requests.

**Pull request merged**
