### PR TITLE
Added `on_pre_dismiss`, `on_open`, `on_pre_open` events fix `on_dismiss`

### PR DESCRIPTION
**Pull request by Neizvestnyj**
```py
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
MDScreen:

    MDRaisedButton:
        id: button
        text: "Open"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [
            {
                "text": f"Item {i}",
                "viewclass": "OneLineListItem",
                "on_release": lambda x=f"Item {i}": self.menu_callback(x),
            } for i in range(5)
        ]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_open=lambda *args: print('on_open'))
        self.menu.bind(on_pre_open=lambda *args: print('on_pre_open'))
        self.menu.bind(on_dismiss=lambda *args: print('on_dismiss'))
        self.menu.bind(on_pre_dismiss=lambda *args: print('on_pre_dismiss'))

    def menu_callback(self, text_item):
        print(text_item)
        self.menu.dismiss()

    def build(self):
        return self.screen


Test().run()
```

https://user-images.githubusercontent.com/40869738/205523984-f9a3776e-2110-4ebc-97a6-80da8d4777ab.mp4

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
While there are no tests, these changes cannot be merged.

**Comment by Neizvestnyj** [comment]
> While there are no tests, these changes cannot be merged.

No problem. If test will be done, let me know, I add `:versionadded 1.2.0` to 3 new events, and then you can merge it.

**Comment by Neizvestnyj** [comment]
Can I change this code to match version 1.2.0 and you will merge?

**Comment by HeaTTheatR** [comment]
The PR is deprecated due to the new API of the KivyMD library 2.0.0 version

**Pull request closed without merging**
