### PR TITLE
Redid MDChip to allow for multiple select and action chips

### PR DESCRIPTION
**Pull request by Guhan-SenSam**
### Description of the Feature
The current system of MDChips doesn't quite follow Material Design component guidelines. It doesn't allow for the creation `action chips` and allow for the selection of `multiple chips`. I have rewritten the code of MDChip to allow

- An attribute of the `MDChipContainer` widget that will determine the type of all the chips that are children of it. There are two types of chips `action chips` and `selection chips`.
- `action chips` will execute a function on click that can be defined by the user using the `on_press` method. The chips will not change color to depict selection.
- `selection chips` act similar to the existing system of MDChips. These chips can behave in two different ways depending on the attribute `multiple` of the parent `MDChipContainer`.
- If `multiple` is `True` then multiple chips can be selected. Chips do not display ticks even if the attribute `tick` is `True`
- if `multiple` is `False` (Which is default) then only one chip can be selected at a time.. Chips can display ticks depending on the attribute `tick`.
- When `selection chips` are used the text of all selected chips are returned as a list in the attribute `selected` of `MDChipContainer`. This is a read only attribute
-  Each chip has an `active` attribute that when set to `True` will cause that chip to be selected provided its not a `action chip`

Basically the `MDChipContainer` acts as a container for all chips and it decides the type of chips that it can hold. But each widget can define its own function to call if its pressed. 

This is an example for using the MDChipContainer in selection mode(Default mode):
```from kivymd.app import MDApp
from kivy.lang import Builder
kv = '''
MDChipContainer:
    spacing:'10dp'
    pos_hint:{'center_x':.5, 'center_y':.5}
    size_hint:None,None
    MDChip:
        text:'Account'
        icon:'account'
    MDChip:
        text:'Account Supervisor'
        icon:'account-supervisor'
    MDChip:
        text:'Account-hard-hat'
        icon:'account-hard-hat'
'''

class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)

TestApp().run()
```
ezgif com-gif-maker

This is with the multiple property set to True:
```from kivymd.app import MDApp
from kivy.lang import Builder
kv = '''
MDChipContainer:
    spacing:'10dp'
    pos_hint:{'center_x':.5, 'center_y':.5}
    size_hint:None,None
    multiple:True
    MDChip:
        text:'Account'
        icon:'account'
    MDChip:
        text:'Account Supervisor'
        icon:'account-supervisor'
    MDChip:
        text:'Account-hard-hat'
        icon:'account-hard-hat'
'''
```
ezgif com-gif-maker(1)

This is an example for action chips:
```
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.toast import toast
kv = '''

MDChipContainer:
    spacing:'10dp'
    pos_hint:{'center_x':.5, 'center_y':.5}
    size_hint:None,None
    type:'action'
    MDChip:
        text:'Account'
        icon:'account'
        on_release:app.show(self)
    MDChip:
        text:'Account Supervisor'
        icon:'account-supervisor'
        on_release:app.show(self)
    MDChip:
        text:'Account-hard-hat'
        icon:'account-hard-hat'
        on_release:app.show(self)
'''

class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def show(self,ele):
        toast(ele.text)

TestApp().run()

```
ezgif com-gif-maker(2)

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@Guhan-SenSam 
Thanks for this PR!
Unfortunately, your PR request does not have any code examples. Therefore, we cannot look at what you describe in the description for your PR.

**Comment by kulothunganug** [comment]
@Guhan-SenSam Please also update kitchen-sink as well as [usage](https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/assets/usage/Components-Chip.txt)

**Comment by Guhan-SenSam** [comment]
Yea I added some examples and changed kitchen sink and usage. Sorry for for all the commits. I had some problems with my github desktop client.

**Comment by HeaTTheatR** [comment]
@Guhan-SenSam Your labels are not centered. The paddings are not proportional and, most likely, it will look even worse on a mobile device...

**Comment by Guhan-SenSam** [comment]
Yep I improved the demo

**Pull request closed without merging**
