### PR TITLE
Great formatting

### PR DESCRIPTION
**Pull request by ArtemSBulgakov**
I love when everything is beautiful.
So I made one-style docstring for every file. I added links to MD pages. I renamed several files to be same as MD component.
I tried almost everywhere made one format.

Fixed some bugs in demo.

### CODE REVIEW

**Comment by ArtemSBulgakov** [comment]
After that, no bugs appeared in the code. The demo works correctly.
You can merge

**Comment by HeaTTheatR** [comment]
sys.path.append(os.path.abspath(__file__).split('demos')[0]) in main.py
file need for correctly worked on MacOS!

вс, 24 февр. 2019 г. в 12:15, Mountaino <notifications@github.com>:

**Comment by HeaTTheatR** [comment]
@Mountaino No need to rename files, since you will break backward compatibility!

**Comment by ArtemSBulgakov** [comment]
File names need to be meaningful and correct. It is beta version of library and backward compatibility does not need.

**Comment by ArtemSBulgakov** [comment]
Thank you.

Wait for the Theming System from me. The existing system is so poor

**Comment by yunus-ceyhan** [comment]
when i run kitchen_sink getting that error.

```
File "/storage/emulated/0/KivyMD/kivymd/navigationdrawer.py", line 404, in add_widget
     super(MDNavigationDrawer, self).add_widget(widget, index, canvas)
 TypeError: add_widget() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by ArtemSBulgakov** [comment]
Can I rename grid.py to imagelists.py ?

**Comment by ArtemSBulgakov** [comment]
And elevationbehavior.py to elevation.py
ripplebehavior.py to ripple.py
date_picker.py join with time_picker.py and theme_picker.py to pickers.py
stackfloatingbuttons.py move to button.py
accordionlistitem.py move to accordion.py
?

**Comment by ArtemSBulgakov** [comment]
It will be more understandable for people and more logical.

**Comment by HeaTTheatR** [comment]
@Mountaino No need rename ripplebehavior.py. The rest is possible, but check carefully.

**Pull request merged**
