### PR TITLE
Elevation behavior docs update.

### PR DESCRIPTION
**Pull request by podraco**
### Description of Changes
Updated docs of the Elevation behavior

### CODE REVIEW

**Comment by podraco** [comment]
docs updated.

**Comment by podraco** [comment]
do not merge, found an error in a code example

**Comment by HeaTTheatR** [comment]
@podraco You didn't `git pull` before committing and overwrite the changes I do recently.

**Comment by HeaTTheatR** [comment]
@podraco 

Снимок экрана 2021-02-10 в 22 00 27

Снимок экрана 2021-02-10 в 22 01 04

**Comment by podraco** [comment]
The branch stated it was up to date with master, let me review and add your changes

**Comment by podraco** [comment]
Added your changes to the file I modified.
Reviewed the examples and other minimal stuff I did not see the first time.

**Comment by HeaTTheatR** [comment]
@podraco But I still don't understand what changes happened in the behavior of `elevation` and why the library uses the old implementation of `elevation`. And if a new implementation is used, where exactly? We do not tell the user anything about this. This is what I want to know first of all...

**Comment by podraco** [comment]
this changes are merely a for documentation.

**Comment by podraco** [comment]
The new implementation uses the old names, while the old code was modified to allow overwriting some instructions where the performance is more important than aesthetics.

**Comment by podraco** [comment]
the explanation is inside
`How to improve the performance`

**Pull request merged**
