### PR TITLE
Fix same icon MDFloatingActionButtonSpeedDial

### PR DESCRIPTION
**Pull request by VICTORVICKIE**
### Description of Changes
This fix allows user to use same icon for multiple speed dials in MDFloatingActionButtonSpeedDial
but data need to be changed as follows, 
{'icon_name': 'name to be displayed'}
```
data = {
            'Python':'plus' ,
            'PHP':'plus' ,
            'C++':'plus' ,
        }
```

### Screenshots
Screenshot_1

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@VICTORVICKIE 
Thanks for PR!
The following data structure is not correct from the point of view of the Python programming language:

```python
data = {
            'plus': 'Python',
            'plus': 'PHP',
            'plus': 'C++',
        }
```
And then, I'm not sure that we should implement such a possibility as using two identical icons for a stack of buttons.

**Comment by VICTORVICKIE** [comment]
Two identical icons may give app devs more access,
and I've commented wrong data dict structure
```
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDFloatingActionButtonSpeedDial:
        data: app.data
        root_button_anim: True
'''


class Example(MDApp):
    data = {
        'Python':'plus' ,
        'PHP':'plus' ,
        'C++':'plus' ,
    }

    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
@VICTORVICKIE 
Have you checked these changes on the Kitchen demo application?

**Comment by VICTORVICKIE** [comment]
Checked and i ll send another updated PR

**Pull request closed without merging**
