### PR TITLE
Console scripts

### PR DESCRIPTION
**Pull request by JulianOrteil**
### Description of the problem

#1306

### Description of Changes

Modified ``setup.py``

### Screenshots of the solution to the problem

image

### CODE REVIEW

**Comment by kulothunganug** [comment]
Maybe `kivymd.{command}` will be more specific to kivymd lib

**Comment by HeaTTheatR** [comment]
@JulianOrteil Will there be name conflicts with other scripts in this way?

**Comment by JulianOrteil** [comment]
@HeaTTheatR It's certainly possible if the user has other programs or scripts on ``PATH`` with these names. I'm not partial to any naming scheme, so if you prefer something like @Kulothungan16's suggestion, that isn't an issue (albeit I've never used dot notation for console scripts so I can't comment on if that specific scheme will work on every platform).

**Comment by HeaTTheatR** [comment]
@JulianOrteil Let's try to do as @Kulothungan16's suggested. The functionality of the developer tools will be expanded and in the future there may be problems with the names of other scripts.

**Comment by JulianOrteil** [comment]
@HeaTTheatR I have updated the console scripts to reflect the suggestions made by @Kulothungan16. As I don't have access to MacOS or easy access to Linux, I cannot vouch for the compatibility of this command theme with those OS's. They work fine on Windows 10. You'll want to verify those OS's work before merging this PR.

**Pull request merged**
