### PR TITLE
Buttons - Elevation Bugfix and optimization.

### PR DESCRIPTION
**Pull request by podraco**
### Description of Changes
Some buttons kept managing the elevation manually, instead of using the API, thus doing some work over and over again when unnecessary.

Elevation now manages an error value, when the elevation set is below 0, the errorvalue will set elevation to 0.
_elevation now manages an error value, when the elevation set is below 0, the errorvalue will set elevation to 0.

Removed `_elevation_normal`, the value acted as a duplicate of the `elevation` property
`_elevation_raised` is now updated each time `elevation` is set

Added docstring to BaseElevationButton.

Fixed some animations and behaviors when the button changes from disabled to enabled (specially when a button was defined as disabled when the instance was created)

Animation fixed, when a button has an animation running and changes to disabled, the animation is canceled before the _elevation property changes.

### CODE REVIEW

**Comment by podraco** [comment]
this is a branch in my private repo. i spreaded the mods to avoid mixing objetives.
master - was the prior merge
elevation - fixes some elevation bugs in the button class
MDToolbar - Fixes an error in which an animation was running when the floating button was not set. This will be the next push after elevation.

**Comment by HeaTTheatR** [comment]
> MDToolbar - Fixes an error in which an animation was running when the floating button was not set. This will be the next push after elevation.

https://github.com/kivymd/KivyMD/commit/985ba667746ff0db83fdbbdba510620083e2047d#diff-9488ea7a91570dcebddccd535d5940567e7efbdb7cb20d8ae6a248b2a33fb09d

**Comment by HeaTTheatR** [comment]
@podraco 
Please check the changes on the `Kitchen` demo application before pushing. For example, this `pull reques`t broke the display of the background color for the `MDCard` class:

Снимок экрана 2021-02-12 в 14 41 53

**Comment by HeaTTheatR** [comment]
@podraco 

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDBoxLayout:
        pos_hint: {"center_x": .5, "center_y": .5}
        adaptive_size: True
        spacing: "56dp"
        padding: "56dp"

        MDCard:
            size_hint: None, None
            size: root.width / 2 - dp(56), "180dp"
            radius: [12, 12, 12, 12]  # background is not displayed when using radius

        MDCard:
            size_hint: None, None
            size: root.width / 2 - dp(56), "180dp"

'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
Снимок экрана 2021-02-12 в 15 27 09

**Comment by HeaTTheatR** [comment]
@podraco 

```python
from kivy.lang import Builder
from kivy.uix.behaviors import ButtonBehavior

from kivymd.app import MDApp
from kivymd.uix.behaviors import CircularElevationBehavior, \
    CircularRippleBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
#:import Animation kivy.animation.Animation


<WidgetWithShadow>
    size_hint: [None, None]
    elevation: 6
    animation_: None
    md_bg_color: [1] * 4
    on_size:
        self.radius = [self.height / 2] * 4
    on_press:
        if self.animation_: \
        self.animation_.cancel(self); \
        self.animation_ = Animation(_elevation=self.elevation + 6, d=0.08); \
        self.animation_.start(self)
    on_release:
        if self.animation_: \
        self.animation_.cancel(self); \
        self.animation_ = Animation(_elevation=self.elevation, d=0.08); \
        self.animation_.start(self)


MDFloatLayout:

    WidgetWithShadow:
        size: [root.size[1] / 2] * 2
        pos_hint: {"center": [0.5, 0.5]}
'''


class WidgetWithShadow(
    CircularElevationBehavior,
    CircularRippleBehavior,
    ButtonBehavior,
    MDBoxLayout,
):
    def __init__(self, **kwargs):
        # always set the elevation before the super().__init__ call
        # self.elevation = 6
        super().__init__(**kwargs)

    def on_size(self, *args):
        self.radius = [self.size[0] / 2]


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

Cannot set `md_bg_color` parameter for `WidgetWithShadow` widget.

**Comment by podraco** [comment]
Found the error. This line is making the background transparent, I'm looking through docs to see why
```
            source: root.background

```
It's inside the card definition.

**Comment by podraco** [comment]
The error was that the texture was being drawn as transparent inside the event instead of using the image as background.
``` py
def on_radius(self, instance, value):
        if self.radius != [0, 0, 0, 0]:
            self.background = f"{images_path}/transparent.png"
```

**Comment by HeaTTheatR** [comment]
@podraco This method does not exist.

**Comment by HeaTTheatR** [comment]
@podraco
> Please check the changes on the `Kitchen` demo application before pushing. For example, this `pull reques`t broke the display of the background color for the `MDCard` class:
> 

> Снимок экрана 2021-02-12 в 14 41 53

Fix https://github.com/kivymd/KivyMD/commit/8dcd24ac2ee1755268bf84b9bf72a98186071f58

**Comment by HeaTTheatR** [comment]
> @podraco
> 
> ```python
> from kivy.lang import Builder
> from kivy.uix.behaviors import ButtonBehavior
> 
> from kivymd.app import MDApp
> from kivymd.uix.behaviors import CircularElevationBehavior, \
>     CircularRippleBehavior
> from kivymd.uix.boxlayout import MDBoxLayout
> 
> KV = '''
> #:import Animation kivy.animation.Animation
> 
> 
> <WidgetWithShadow>
>     size_hint: [None, None]
>     elevation: 6
>     animation_: None
>     md_bg_color: [1] * 4
>     on_size:
>         self.radius = [self.height / 2] * 4
>     on_press:
>         if self.animation_: \
>         self.animation_.cancel(self); \
>         self.animation_ = Animation(_elevation=self.elevation + 6, d=0.08); \
>         self.animation_.start(self)
>     on_release:
>         if self.animation_: \
>         self.animation_.cancel(self); \
>         self.animation_ = Animation(_elevation=self.elevation, d=0.08); \
>         self.animation_.start(self)
> 
> 
> MDFloatLayout:
> 
>     WidgetWithShadow:
>         size: [root.size[1] / 2] * 2
>         pos_hint: {"center": [0.5, 0.5]}
> '''
> 
> 
> class WidgetWithShadow(
>     CircularElevationBehavior,
>     CircularRippleBehavior,
>     ButtonBehavior,
>     MDBoxLayout,
> ):
>     def __init__(self, **kwargs):
>         # always set the elevation before the super().__init__ call
>         # self.elevation = 6
>         super().__init__(**kwargs)
> 
>     def on_size(self, *args):
>         self.radius = [self.size[0] / 2]
> 
> 
> class Example(MDApp):
>     def build(self):
>         return Builder.load_string(KV)
> 
> 
> Example().run()
> ```
> 
> Cannot set `md_bg_color` parameter for `WidgetWithShadow` widget.

But this error exists.

**Comment by podraco** [comment]
### Example Code
``` py
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''

<SaS@RoundedRectangularElevationBehavior+BackgroundColorBehavior>:
    radius:[10]*4
    elevation:10
    background: "Captura de pantalla de 2021-02-11 17-38-36.png"
    canvas.before:
        Color:
            rgba: [1]*4
        RoundedRectangle:
            radius:self.radius
            pos:self.pos
            size:self.size
            source: self.background

MDScreen:

    MDBoxLayout:
        pos_hint: {"center_x": .5, "center_y": .5}
        # adaptive_size: True
        spacing: "56dp"
        padding: "56dp"

        MDCard:
            size: root.width / 2 - dp(56), "180dp"
            md_bg_color: [1]*4
            radius: 0  # background is not displayed when using radius
            background: "72320162_785995311851085_6095325768672346112_n.jpg"

        MDCard:
            size: root.width / 2 - dp(56), "180dp"
            md_bg_color: [1]*4
            radius: 10  # background is not displayed when using radius
            background: "72320162_785995311851085_6095325768672346112_n.jpg"
        #
        MDCard:
            size: root.width / 2 - dp(56), "180dp"
            md_bg_color: [1]*4
            radius: 24
            background: "72320162_785995311851085_6095325768672346112_n.jpg"

'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()

```
### Resource:
72320162_785995311851085_6095325768672346112_n

Example with background="72320162_785995311851085_6095325768672346112_n.jpg"
Captura de pantalla de 2021-02-12 12-43-36

(the pull was merged before i could push the patch. File affected: kivymd.uix.card.MDCard.on_radius)

**Comment by HeaTTheatR** [comment]
@podraco 

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDBoxLayout:
        pos_hint: {"center_x": .5, "center_y": .5}
        adaptive_size: True
        spacing: "56dp"
        padding: "56dp"

        MDCard:
            size_hint: None, None
            size: root.width / 2 - dp(56), "180dp"
            radius: [12, 12, 12, 12]  # md_bg_color is not displayed when using radius

        MDCard:
            size_hint: None, None
            size: root.width / 2 - dp(56), "180dp"

'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
@podraco 

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.behaviors import CircularElevationBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
<ExampleCircle>
    size_hint: None, None
    size: "60dp", "60dp"
    md_bg_color: 1, 0, 1, 1


MDScreen:

    ExampleCircle:
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class ExampleCircle(CircularElevationBehavior, MDBoxLayout):
    def __init__(self, **kwargs):
        self.elevation = 48
        super().__init__(**kwargs)

    def on_size(self, *args):
        self.radius = [self.size[0] / 2]


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

Снимок экрана 2021-02-12 в 21 59 28

**Comment by podraco** [comment]
seems like it's missing a call... let me test something...
seems like when someone sets the deffault vaule inside init before the super call, the shadow update is not called, but if you set the value after, the call is correctly deployed

**Comment by HeaTTheatR** [comment]
@podraco No, it won't work...

**Comment by podraco** [comment]
Examples:
``` py
class ExampleCircle(CircularElevationBehavior, MDBoxLayout):
    def __init__(self, **kwargs):
        self.elevation = 48
        super().__init__(**kwargs)
```
Captura de pantalla de 2021-02-12 13-04-25

``` py
class ExampleCircle(CircularElevationBehavior, MDBoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.elevation = 48
```
Captura de pantalla de 2021-02-12 13-03-09

**Comment by HeaTTheatR** [comment]
@podraco The shadow is on the top layer...

Снимок экрана 2021-02-12 в 22 04 14

**Comment by HeaTTheatR** [comment]
@podraco 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.behaviors import CircularElevationBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
<ExampleCircle>
    size_hint: None, None
    size: "60dp", "60dp"
    md_bg_color: 1, 0, 1, 1


MDScreen:

    ExampleCircle:
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class ExampleCircle(MDBoxLayout, CircularElevationBehavior):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.elevation = 48

    def on_size(self, *args):
        self.radius = [self.size[0] / 2]


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by podraco** [comment]
that's because of how python combines inheritances, i changed this
``` py
class BackgroundColorBehavior(Widget):
```
To this
``` py
class BackgroundColorBehavior(CommonElevationBehavior):
```
file: kivymd.uix.behaviors.BackgroundColorBehavior

This changes the order in which the canvas instructions are clipped.

**Pull request merged**
