### PR TITLE
Add markup support for buttons

### PR DESCRIPTION
**Pull request by svareille**
Add possibility to use text markup inside buttons.

### CODE REVIEW

**Review by HeaTTheatR — COMMENTED** [review]
It seems to me that it does not work.

**Comment by svareille** [comment]
The default behaviour of kivy's labels is to have text markup disabled. These buttons act the same way.
In fact you have to set "markup: True" inside your button definition to use markup: 
``` Python
MDFillRoundFlatButton:
    text: "1[sup]st[/sup] button"
    markup: True
    elevation_normal: 2
    opposite_colors: True
    size_hint: 0.8, 0.8
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
```

**Review by HeaTTheatR — COMMENTED** [review]
You don't even have a markup parametr - https://github.com/HeaTTheatR/KivyMD/pull/76/commits/9d69f5dc5357f76d7f9be3e1bc55ffac3a2ad438#diff-388bedbbd6a85396a0abaa4e81d04c19R366
It just won't work

**Comment by svareille** [comment]
`MDLabel` inherit from kivy's `Label` so `markup` is avaliable.
I tested it before submitting: at least `MDFillRoundFlatButton`, `MDRoundFlatIconButton` and `MDRectangleFlatIconButton` works with markup.

**Review by HeaTTheatR — COMMENTED** [review]
I think it would not be bad to make these changes for all classes of buttons.

**Comment by svareille** [comment]
I didn't inspect the full tree, but I think that every button inherit from at least one of these classes. I will do some tests.

**Comment by HeaTTheatR** [comment]
@SimonVareille I just do not have time to check it all on my own. I am also working on a lot of changes and new classes.

**Comment by svareille** [comment]
Ok, I will test it for every buttons ant let you know.

**Comment by svareille** [comment]
It works with every buttons:
image

Just by adding `markup: True` and the tag we want (modification of the 'buttons' section in `screens.py` for the kitchen_sink example):
```Python
MDFlatButton:
    text: 'MD[u]Flat[/u]Button'
    pos_hint: {'center_x': .5}
    markup: True

 MDRaisedButton:
    text: "MDRaised[sub]Button[/sub]"
    elevation_normal: 2
    opposite_colors: True
    pos_hint: {'center_x': .5}
    markup: True

MDRectangleFlatButton:
    text: "MDRectangle[b]Flat[/b]Button"
    pos_hint: {'center_x': .5}
    markup: True

...
```
(full code [here](https://gist.github.com/SimonVareille/ef99db3364e06579ec84ab01f439dd57))

**Comment by HeaTTheatR** [comment]
@SimonVareille You ran tests with the current pool?

**Comment by svareille** [comment]
I ran tests with the version of `kivymd/button.py` I propose, witch is based on your current master branch.

**Pull request merged**
