### PR TITLE
Fix `TypeError: 'int' object is not iterable` in `MDSlider`

### PR DESCRIPTION
**Pull request by Neizvestnyj**
Fixed a bug
```py
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen

    MDSlider:
        min: 0
        max: 100
        value: 40
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Please run the command `pre-commit run --all-files` before pushing.

**Comment by Neizvestnyj** [comment]
> 

I just changed the file directly on the github site)

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 
Снимок экрана 2021-11-21 в 14 57 13

**Comment by Neizvestnyj** [comment]
@HeaTTheatR Do I need to do something like this in the kivymd folder? It's just that I've been using PyCharm for many years, and there this process boils down to 2 clicks)
```
git branch fix_slider
git checkout fix_slider
git add /kivymd/uix/slider
git commit -m "Fix `TypeError: 'int' object is not iterable` in `MDSlider`"
pre-commit run --all-files
git push --set-upstream origin fix_slider
```

**Comment by HeaTTheatR** [comment]
@Neizvestnyj https://github.com/kivymd/KivyMD#setup-environment

**Comment by Neizvestnyj** [comment]
This is somehow very inconvenient... `An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?`

**Comment by HeaTTheatR** [comment]
@Neizvestnyj It is very convenient.

**Comment by Neizvestnyj** [comment]
@HeaTTheatR Can you tell me in detail once how I can do it? Here I have a downloaded archive of the kivymd library, what's next?

**Comment by sollarp** [comment]
I'm facing the same issue as you @Neizvestnyj. Read about this will give you a hint.
https://www.blopig.com/blog/2020/10/improving-your-python-code-quality-using-git-pre-commit-hooks/

**Pull request closed without merging**
