### PR TITLE
Fix docs build v2

### PR DESCRIPTION
**Pull request by p0lygun**
Description of the problem
The docs CI is failing as we import kivymd in docs generation.

Describe the algorithm of actions that leads to the problem
This happens because the version of the package is defined in the __init__.py of kivymd.
When importing that it also runs [this](https://github.com/kivymd/KivyMD/blob/master/kivymd/__init__.py#L64) line, which then imports kivy, this issue should be fixed in the latest kivy, but its best to have version info in a separate file

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
Is this PR ready to merge?

**Comment by p0lygun** [comment]
yes, all build system should work the same, but if anything breaks please feel free to ping me

**Comment by HeaTTheatR** [comment]
Okay, thanks

**Comment by D111sP** [comment]
Hello everyone, the large Materialyoucolor library does not want to work on a 32-bit system

**Comment by D111sP** [comment]
ImportError: dlopen failed: "/data/data/com.autograd.ag_emp/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is 64-bit instead of 32-bit

**Comment by HeaTTheatR** [comment]
Are 32-bit systems still supported?

**Comment by T-Dynamos** [comment]
Did you use recipe for building?

> ImportError: dlopen failed: "/data/data/com.autograd.ag_emp/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is 64-bit instead of 32-bit

**Comment by p0lygun** [comment]
why is this discussion taking place in the PR ?

**Pull request merged**
