### PR TITLE
Fixed MDBottomAppBar notch transparency

### PR DESCRIPTION
**Pull request by quitegreensky**
### Description of Changes
Fixed the transparency issue in `MDBottomAppBar` by using `Mesh` and giving a custom curve to it.

### Screenshots

Untitled

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@quitegreensky 
Great job!
There are two questions: have you tested these changes on mobile?
Can the rounding be smoother? The screenshot shows that there are sharp corners where a smoother should be.

Снимок экрана 2021-01-29 в 00 39 31

**Comment by quitegreensky** [comment]
@HeaTTheatR It looks smoother now. also i will try to build kitchen_sink for android and let you know if there is any problem.
Untitled

EDIT:
@HeaTTheatR 
On Android:
photo_2021-01-28_02-37-45

**Comment by quitegreensky** [comment]
@HeaTTheatR  According to [spec](https://material.io/components/app-bars-bottom#anatomy) placing FAB outside of the bottom app bar is not recommended. so is it necessary to keep `Free-End` and `Free-Center` options for FAB?
Untitled

**Comment by HeaTTheatR** [comment]
> @HeaTTheatR According to [spec](https://material.io/components/app-bars-bottom#anatomy) placing FAB outside of the bottom app bar is not recommended. so is it necessary to keep `Free-End` and `Free-Center` options for FAB?
> Untitled

Yes, there should be such features. Material Design does not recommend this, but it is possible to do so.

**Comment by HeaTTheatR** [comment]
@quitegreensky 
Do you have any news on this pull request? Have you taken the time to test these changes on Android device?

**Comment by quitegreensky** [comment]
@HeaTTheatR  This is my test results. I didn't notice any issues on my own device by now.

https://user-images.githubusercontent.com/55235027/106598398-8593c900-650c-11eb-8396-92f999a9d414.mp4

https://user-images.githubusercontent.com/55235027/106599079-6cd7e300-650d-11eb-994c-7c3847256400.mp4

**Comment by HeaTTheatR** [comment]
@quitegreensky 
Excellent!
It seems to me that the distance between the FAB and the toolbar is very different ...

106016732-d0f34500-60d0-11eb-9c03-44cbef135d7a

**Comment by HeaTTheatR** [comment]
@quitegreensky One more question. `Mesh` instructions require constant rendering of the screen. Do these changes provide a method to stop the updates of these instructions?

**Comment by quitegreensky** [comment]
> 
> 
> @quitegreensky
> Excellent!
> It seems to me that the distance between the FAB and the toolbar is very different ...
> 
> 106016732-d0f34500-60d0-11eb-9c03-44cbef135d7a

@HeaTTheatR [spec](https://material.io/components/app-bars-bottom#behavior) hasn't defined the spacing between toolbar and FAB as i searched. I changed it to `dp(4)` for now which is correct i think. I also solved some other mathematical issues. but i don't understand your question about stopping the updates of `Mesh`. I've bound the method `_update_canvas` to certain events which will update the mesh only when needed. so i don't think if there is a constant rendering of screen.  
photo_2021-02-01_19-38-40

**Comment by darpan5552** [comment]
image

I think notch should be a combination of 2 Bezier curves. Anyway, congrats for the work you put in.

**Comment by HeaTTheatR** [comment]
@darpan5552 I think we'll come back to this question a little later...

**Comment by quitegreensky** [comment]
@darpan5552 yes but its very slow yo calculate the points on a bezier without using something like numpy.

**Comment by HeaTTheatR** [comment]
@quitegreensky So it will work faster with `NumPy`?

**Comment by quitegreensky** [comment]
sina, [03.02.21 13:27]
> @quitegreensky So it will work faster with NumPy?

It's not a big problem for calculating circles to use pure python but in case of using bezier yes it's faster to use `numpy` but it will add another dependency only for this situation. of cource we can consider using `cython` which requires it's recipe to work.

**Comment by HeaTTheatR** [comment]
@quitegreensky I think we need to create a new issue labeled `Enhancement` to come back to this issue in the future. Dependency `NumPy` for just one task is not a good solution.

**Comment by quitegreensky** [comment]
@HeaTTheatR By using kivy's `Bezier` instruction to draw a bezier curve line, it already calculates all vertices we need but seems its not possible to somehow have access and return those points.

**Comment by darpan5552** [comment]
@quitegreensky 
This widget has primary usage in mobile devices. So, user won't be changing size of screen now & then. In this context, bezier curves wouldn't be an extra load, rather it provides an elegant way for UI designers to make user do almost everything on a single screen.

Yes, i visited bezier.py documentation before making a comment here. Might be a modification required to make it return the points.

**Comment by HeaTTheatR** [comment]
@quitegreensky, @darpan5552
Unfortunately, I cannot help with this problem as I have not yet delved into the `Mesh` instructions...

**Pull request merged**
