### PR TITLE
Fix for #834

### PR DESCRIPTION
**Pull request by podraco**
### Description of Changes
Fix for #834
The canvas of the background was drawn over the children widgets.
fixed background canvas layer

#### Code example:
```py
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
<TheCard@MDCard>:
    orientation: "vertical"
    padding: "8dp"
    size_hint: None, None
    size: "280dp", "180dp"
    md_bg_color:1,0,1,0.0

    MDLabel:
        text: "Title"
        theme_text_color: "Secondary"
        size_hint_y: None
        height: self.texture_size[1]
        canvas.before:
            Color:
                rgb:1,0,0
            Rectangle:
                pos:self.pos[0]-20,self.pos[1]-20
                size:self.size

    MDSeparator:
        height: "1dp"

    MDLabel:
        text: "Body"


Screen:
    TheCard:
        pos_hint: {"center": [0.5, 0.5]}

"""


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)


TestApp().run()
with the alpha of md_bg_color set to 1:
```
Before:
Captura de pantalla de 2021-02-11 02-24-32

After:
Captura de pantalla de 2021-02-11 02-48-38

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@podraco Something strange is happening with your changes. Your pull requests contain changes that were already made in the previous pull request ...

**Comment by podraco** [comment]
Merge master into my personal branch, I'm still unable to do a direct git pull to the master branch

**Comment by podraco** [comment]
Just included your last changes to the docs

**Comment by abdul-yusuf** [comment]
Still having this problem, using kivymd master branch.  i can see the children widget of the card need help pls

**Pull request merged**
