### PR TITLE
WIP - MDTabs: bugfixes and improvements

### PR DESCRIPTION
**Pull request by podraco**
### Description of Changes

- Fixed animation, issue #770

- Fixed tab size,  issue #874

- Fixed toggle behavior missing group release.

- Fixed Toggle behavior when the tab container is displayed on screen (the 
current label wasn't toggled down, and the group wasn't released)

- Simplify the work with icons, text and mixed labels.

- Added documentation for every new property.

- Fixed some minor issues.

- Kitchen sink demo was updated.

- Indicator canvas instruction fixed:
The prior method used the class instance instead of a group name inside  the canvas layers.
This method ensures that the instruction referred to is always the correct.

- Minor doc updates on event description.

- Indicator Animation simplified.

- This fix allows the indicator to change size every time theres a label 
size update.

- Removed some unused kv code

- Simplified Android Animation processing.

#### NEW:

1.- you can set the title label directly with text in the current 
font_style for buttons.

2.- You can now set the icon easier and edit it in a simplified way for 
dynamic title labels.

3.- Title label complies with Material IO spec definitions.

4.- You can set the title label mode for mixed labels (Modes available `"Lead"`, `"Top"`) inside each tab.

5.- You can now force a mode for every tabs label title.

6.- The scroll_view in which the title labels are stored now changes size depending on the mode selected. (only works for fixed mode. Done inside class MDTabs():)

7.- Now you can get the slides list directly from class MDTabs.

8.- the tabs label minimum size is set to 90 dpi as the Material IO 
requires.

9.- removes some trigger updates that weren't necessary. (duplicated the behavior form MDLabel, and its container.)

10.- The kitchen sink demo features the current simplified method to update the tab's label.

#### Before

https://user-images.githubusercontent.com/5509325/108486224-79756e80-7263-11eb-89e8-1af9ee47bcd5.mp4

#### After

https://user-images.githubusercontent.com/5509325/108486236-7c705f00-7263-11eb-8b20-993e48198265.mp4

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@podraco Good job!
As far as I understand, we don't need to merge these changes with the master branch yet?..

**Comment by podraco** [comment]
I believe It can be merged, but I'm not sure if the docs are correct

**Comment by HeaTTheatR** [comment]
@podraco 
Why aren't you testing the changes in the demo application?

```python
    def on_release(self):
        self.tab_bar.parent.dispatch("on_tab_switch", self.tab, self, self.text)
```

**Comment by HeaTTheatR** [comment]
@podraco

https://user-images.githubusercontent.com/16930280/109657882-08915900-7b77-11eb-91ab-8b3deb199276.mov

**Comment by HeaTTheatR** [comment]
@podraco If you have made changes to the Tabs class, you should test the functionality of the demo application completely.

**Comment by podraco** [comment]
?????
I used the demo and the examples in the docs to see if it worked properly. In my end didn't show any error.

**Comment by HeaTTheatR** [comment]
@podraco 
The demo application uses all the widgets in the library, and if we have made any changes, we must first test them in the demo application. On all counts. Since, for example, the element "Theming colors" uses tabs ...

**Comment by podraco** [comment]
I didn't see any problem, sorry.
That's why the second pr fixed what was left broken

**Pull request merged**
