### PR TITLE
Fixed bug with adding widget to MDNavigationDrawer on android

### PR DESCRIPTION
**Pull request by ArtemSBulgakov**
Fixed a bug in https://github.com/HeaTTheatR/KivyMD/pull/28#issuecomment-466776146

### CODE REVIEW

**Comment by yunus-ceyhan** [comment]
Another error when try to open MDList looks like previous..

```
   File "/storage/emulated/0/KivyMD/kivymd/list.py", line 317, in add_widget
     super(MDList, self).add_widget(widget, index, canvas)
 TypeError: add_widget() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by yunus-ceyhan** [comment]
MDCard gives same error..

```
File "/storage/emulated/0/KivyMD/kivymd/grid.py", line 303, in add_widget
     super(SmartTile, self).add_widget(widget, index, canvas)
 TypeError: add_widget() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by yunus-ceyhan** [comment]
Download file


```
kivy.lang.parser.ParserException: Parser: File "<inline>", line 5:
 ...
       3:#:import MDSpinner kivymd.spinner.MDSpinner
       4:#:import MDLabel kivymd.label.MDLabel
 >>    5:#:import MDCard kivymd.card.MDCard
       6:
       7:
 ...
 Unable to import package 'kivymd.card.MDCard'
```

**Comment by ArtemSBulgakov** [comment]
Oh... I will check and fix everything now

**Comment by yunus-ceyhan** [comment]
actually there are some other errors but i don't have time, i'll later report..

**Comment by ArtemSBulgakov** [comment]
PyDroid uses development version of Kivy. In 1.10.1 Layout in kivy.uix.layout has correct add_widget function.

**Comment by HeaTTheatR** [comment]
@Mountaino Everything works! Just a person uses a version of Kiwi lower than 1.10.1, as warned in the README file!

**Comment by ArtemSBulgakov** [comment]
You can change source of kivy in PyDroid files.

/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/uix/layout.py
line 91, change
`def add_widget(self, widget, index=0):`
to
`def add_widget(self, widget, index=0, canvas=None):`

and line 97
`return super(Layout, self).add_widget(widget, index)`
to
`return super(Layout, self).add_widget(widget, index, canvas)`

**Comment by Mountaino** [comment]
> @Mountaino Everything works! Just a person uses a version of Kiwi lower than 1.10.1, as warned in the README file!

I have a error too

**Comment by HeaTTheatR** [comment]
@Mountaino

**Comment by ArtemSBulgakov** [comment]
For working Grid lists in PyDroid you should

in file
/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/uix/floatlayout.py
line 134, change
`def add_widget(self, widget, index=0):`
to
`def add_widget(self, widget, index=0, canvas=None):`

and line 140
`return super(FloatLayout, self).add_widget(widget, index)`
to
`return super(FloatLayout, self).add_widget(widget, index, canvas)`

**Comment by ArtemSBulgakov** [comment]
Unfortunately, upgrading Kivy in PyDroid is impossible, even through the terminal

**Comment by yunus-ceyhan** [comment]
@Mountaino Thank you so much for making it clear, I'll change those lines which you suggested in Pydroid.

**Pull request merged**
