### PR TITLE
Fixed unbinding problem from theme_cls

### PR DESCRIPTION
**Pull request by quitegreensky**
#723 #739 This PR will unbind the bound properties from `theme_cls` which fixes the performance degeneration and memory leaks and improves the performance a lot.

### CODE REVIEW

**Comment by kulothunganug** [comment]
Gettings strange behaviors **after this commit**.

https://user-images.githubusercontent.com/63696279/103333194-0cc7ca00-4a93-11eb-8fa3-177c3ba82d41.mp4

**Comment by HeaTTheatR** [comment]
@Kulothungan16 

https://user-images.githubusercontent.com/16930280/103337868-a2f8f180-4a8d-11eb-80d9-3cf9ef4c6ed9.mov

**Comment by markqvist** [comment]
Just chiming in to say I am getting the same problems with theme switching in my app due to this commit. It is no longer possible to switch between light and dark theme, since the correct colors are not set for text and such.

**Comment by HeaTTheatR** [comment]
@markqvist What do you mean?

**Comment by markqvist** [comment]
Ok, that is weird, I see now that this thread is from 2020.

Since https://github.com/kivymd/KivyMD/commit/6bf15b37b41ab6ed4126718711568c43e1ad01e5, switching between dark and light theme is broken for me, and produces the same behaviour as shown in the video above, where most elements do not update their colors to reflect the theme change.

Removing:
```
def dec_disabled(self, *args, **kwargs) -> None:
  callabacks = self.theme_cls.get_property_observers("theme_style")
  for callaback in callabacks:
      if hasattr(callaback, "proxy") and hasattr(
          callaback.proxy, "theme_cls"
      ):
          self.theme_cls.unbind(
              **{
                  "theme_style": getattr(
                      callaback.proxy, callaback.method_name
                  )
              }
          )

  super().dec_disabled(*args, **kwargs)
```

Makes theme switching work again. I realise this automatic unbinding was done to fix a memory leak, but just wanted to note that the behaviour is still there in the head of master.

**Comment by markqvist** [comment]
Ah, I see now the pull request is from 2020, but was not merged until about a month ago.

Other than just setting `theme_cls.theme_style`, is there a better way to switch themes that I am not aware of, or is it indeed broken in master?

**Comment by HeaTTheatR** [comment]
@markqvist I don't understand what problems you are talking about...

**Comment by Shiv-Patil** [comment]
+1, theme switching is not working for me as well. Sometimes the colors get updated, sometimes they do not.
It works when using the library before https://github.com/kivymd/KivyMD/commit/6bf15b37b41ab6ed4126718711568c43e1ad01e5 (e.g https://github.com/kivymd/KivyMD/commit/4a203fe1c27ad1a716847b35beb0d739e0fd557e)

**Comment by HeaTTheatR** [comment]
@Shiv-Patil Attach minimal code that reproduce this bug.

**Comment by Shiv-Patil** [comment]
@HeaTTheatR 
```py
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
AnchorLayout:
    MDBoxLayout:
        orientation: "vertical"
        adaptive_size: True
        MDTextField:
            hint_text: "Field"
            size_hint: None, None
            width: dp(269)
        MDRectangleFlatButton:
            text: "Change theme"
            on_release: app.switch_theme()
"""


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def switch_theme(self):
        self.theme_cls.theme_style = (
            "Dark" if self.theme_cls.theme_style == "Light" else "Light"
        )


if __name__ == "__main__":
    TestApp().run()
```
https://user-images.githubusercontent.com/35653831/197255403-444b956d-7095-494b-b140-a031be650c85.mp4

**Comment by HeaTTheatR** [comment]
@Shiv-Patil Yes, there is a bug with the selected text.

**Comment by HeaTTheatR** [comment]
@Shiv-Patil https://github.com/kivymd/KivyMD/commit/905611d6c5d8553c4ca6bd5ee1c4d2d7ee726c8d


https://user-images.githubusercontent.com/16930280/197324874-db9d4772-f568-45f0-b627-6da2ea25aa1f.mov

**Comment by Shiv-Patil** [comment]
@HeaTTheatR Thanks
Data Table seems to have this issue as well
```py
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.datatables import MDDataTable
kv = """
AnchorLayout:
    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(20)
        adaptive_height: True
        AnchorLayout:
            id: parent
            size_hint_y: None
            height: 200
        MDRectangleFlatButton:
            text: "Change theme"
            pos_hint: {"center_x": 0.5}
            on_release: app.switch_theme()
"""
class TestApp(MDApp):
    def build(self):
        root = Builder.load_string(kv)
        root.ids.parent.add_widget(MDDataTable(size_hint_max_x=500, rows_num=4, column_data=[("C1", 40), ("C2", 40)], row_data=[("1.1", "1.2"), ("2.1", "2.2")]))
        return root
    def switch_theme(self):
        self.theme_cls.theme_style = ("Dark" if self.theme_cls.theme_style == "Light" else "Light")
if __name__ == "__main__":
    TestApp().run()
```
https://user-images.githubusercontent.com/35653831/197328618-f42be6b4-e548-41df-b2b7-1f5f86ed48d6.mp4

**Comment by HeaTTheatR** [comment]
@Shiv-Patil Please create a new issue for the bug.

**Comment by Shiv-Patil** [comment]
#1399

**Pull request merged**
