### PR TITLE
fixes #474

### LINKED ISSUE #474: on_long_touch behaviour does not work correctly when used with MDTabs
### Description of the Bug

on_long_touch behavior does not work correctly when used with MDTabs
if u try to use on_long_touch  with MdTabs 
on_long_touch  is called even when you press once 

### Code and Logs

```python
from kivymd.uix.behaviors import TouchBehavior
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.lang import Builder


kv = """
ScreenManager:
    id : screen_manager
    MainScreen:
        name : "main"
        MDBoxLayout:
            orientation: "vertical"
            spacing : "20dp"
            MDToolbar:
                title: "Long Touch not working"
            MDTabs:
                lock_swiping:True

"""


class MainScreen(Screen, TouchBehavior):
    

    def on_long_touch(self, *args):
        touch = args[0]
        try:
            print(touch.pos)
        except:
            raise


class Temp(MDApp):
    def build(self):
        return Builder.load_string(kv)

if __name__ == "__main__":
    Temp().run()
```

### Versions

* OS: Windows 10
* Python: 3.7.8
* Kivy: 2.0.0rc1
* KivyMD: 0.104.2.dev0

### PR DESCRIPTION
**Pull request by p0lygun**
### Description of Changes
fix for #474 
Tested on kitchen_sink

### CODE REVIEW

**Review by HeaTTheatR — COMMENTED** [review]
Thank you for helping to improve the KivyMD library.
I conducted tests and can say that the problem persists: the MDTabs class reacts to `on_touch_down` as an `on_long_touch` event.

**Comment by p0lygun** [comment]
But the problem is solved when I try 
Can I see please see the code u used while testing out the commit

**Comment by HeaTTheatR** [comment]
@p0lygun 
```python
from kivymd.uix.behaviors import TouchBehavior
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.lang import Builder


kv = """
ScreenManager:
    id : screen_manager
    MainScreen:
        name : "main"
        MDBoxLayout:
            orientation: "vertical"
            spacing : "20dp"
            MDToolbar:
                title: "Long Touch not working"
            MDTabs:
                lock_swiping:True

"""


class MainScreen(Screen, TouchBehavior):
    

    def on_long_touch(self, *args):
        touch = args[0]
        try:
            print(touch.pos)
        except:
            raise


class Temp(MDApp):
    def build(self):
        return Builder.load_string(kv)

if __name__ == "__main__":
    Temp().run()```

**Comment by p0lygun** [comment]
@HeaTTheatR 
try with this code
```python
from kivymd.uix.behaviors import TouchBehavior
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.lang import Builder


kv = """
ScreenManager:
    id : screen_manager
    MainScreen:
        name : "main"
        MDBoxLayout:
            orientation: "vertical"
            spacing : "20dp"
            MDToolbar:
                title: "Long Touch not working"
            MDTabs:
                lock_swiping:True

"""


class MainScreen(Screen,TouchBehavior):
    def on_touch_down(self, *args):
        print("on_touch_down")
    def on_touch_up(self, *args):
        print("on_touch_up")
    def on_long_touch(self, *args):
        print("on_long_touch")


class Temp(MDApp):
    def build(self):
        return Builder.load_string(kv)

if __name__ == "__main__":
    Temp().run()

```
and u are using my fork for kivymd right ?

**Comment by p0lygun** [comment]
its working fine
image

**Comment by HeaTTheatR** [comment]
@p0lygun This does not work!

**Pull request merged**
