### PR TITLE
Removed forced defocusing in the `MDTextField` class in the `set_text` function

### PR DESCRIPTION
**Pull request by Neizvestnyj**
The forced defocusing, which was a crutch, has been removed.

Tests:
```py
from kivy.lang import Builder
from kivy.uix.textinput import TextInput
from kivy.clock import Clock

from kivymd.app import MDApp
from kivymd.utils import asynckivy

KV = """
MDScreen:
    MDBoxLayout:
        id: box
        orientation: "vertical"
        spacing: "20dp"
        adaptive_height: True
        size_hint_x: .8
        pos_hint: {"center_x": .5, "center_y": .5}

        MDTextField:
            hint_text: "Label"
            helper_text: "Error massage"
            mode: "rectangle"
            max_text_length: 5
            use_bubble: True

        MDTextField:
            icon_left: "git"
            hint_text: "Label"
            helper_text: "Error massage"
            mode: "rectangle"
            use_bubble: True

        MDTextField:
            icon_left: "git"
            hint_text: "Label"
            helper_text: "Error massage"
            mode: "fill"
            use_bubble: True

        MDTextField:
            hint_text: "Label"
            helper_text: "Error massage"
            mode: "fill"
            use_bubble: True

        MDTextField:
            hint_text: "Label"
            helper_text: "Error massage"
            use_bubble: True

        MDTextField:
            icon_left: "git"
            hint_text: "Label"
            helper_text: "Error massage"
            use_bubble: True

        MDTextField:
            hint_text: "Round mode"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            use_bubble: True
            
        MDRectangleFlatButton:
            text: 'Start tests'
            pos_hint: {"center_x": .5}
            on_release: app.start_tests()
            
"""


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def start_tests(self):
        Clock.schedule_once(self.insert)
        Clock.schedule_once(self.cut, 1.0)
        Clock.schedule_once(self.paste, 1.5)
        Clock.schedule_once(lambda dt: asynckivy.start(self.do_backspace(dt)), 2.0)

    def insert(self, dt: float):
        for widget in self.root.ids.box.children:
            if issubclass(widget.__class__, TextInput):
                widget.insert_text('Text')

    def cut(self, dt: float):
        for widget in self.root.ids.box.children:
            if issubclass(widget.__class__, TextInput):
                widget.select_all()
                widget.cut()

    def paste(self, dt: float):
        for widget in self.root.ids.box.children:
            if issubclass(widget.__class__, TextInput):
                widget.paste()

    async def do_backspace(self, dt: float):
        for widget in self.root.ids.box.children:
            if issubclass(widget.__class__, TextInput):
                for _ in range(len(widget.text)):
                    await asynckivy.sleep(0.04)
                    widget.do_backspace(from_undo=False, mode='bkspc')


Test().run()

```

No problems were noticed during manual testing. Related to #1207 

**kivy: 2.1.0**

https://user-images.githubusercontent.com/40869738/159165835-ce2a5b88-4cee-4d1d-a337-0cd5a1e25eda.mp4

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Be careful. Tests show visual bugs for these changes!

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj Be careful. Tests show visual bugs for these changes!

Hmm, I don't see any bugs (attached the video to the PR)

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 

https://user-images.githubusercontent.com/16930280/159167667-7f06c769-30dd-4fb8-ba8f-05a6ae891fba.mov


https://user-images.githubusercontent.com/16930280/159167683-ec4e3654-cb6d-4d8a-9628-9b50b1872672.mov


https://user-images.githubusercontent.com/16930280/159167687-cbb27aa6-9547-4c23-85a5-8bd4e40e9102.mov

**Comment by Neizvestnyj** [comment]
@HeaTTheatR Is it good?
https://user-images.githubusercontent.com/40869738/159172518-1744b51c-2081-4e84-910b-6b61379a6204.mp4

**Comment by Neizvestnyj** [comment]
I added a modified version, as for me, it seems to look as expected

https://user-images.githubusercontent.com/40869738/159173016-9106f2fa-4ccb-44ef-b5a8-213e18a3b26e.mp4

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Don't you see the bugs in your last video?

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj Don't you see the bugs in your last video?

No ... If you are talking about a filled text field, there was a graphic bug in it before, I fixed it for the heap

**Comment by Neizvestnyj** [comment]
Or are you talking about the fact that the text should be aligned to the bottom of the cursor?

**Comment by Neizvestnyj** [comment]
Is it works as aspected?

https://user-images.githubusercontent.com/40869738/159277943-f05ffe93-1b3f-4086-851f-264a944dd617.mp4

**Pull request merged**
