### PR TITLE
Address header sort button divide by zero error

### PR DESCRIPTION
**Pull request by nhansendev**
### Description of the problem

Addresses the bug mentioned in #1441 by removing the lines that resize the sort button to have a height of zero, which leads to a divide by zero error when calculating rounded rectangle radius. Visually it looks the same as before the error was fixed since the items being hidden also have opacity toggled as needed.

### Describe the algorithm of actions that leads to the problem

See the example code in the [documentation for datatables](https://kivymd.readthedocs.io/en/1.1.1/components/datatables/). Zero-division errors only appeared when the mouse moved out of one of the **sortable** header titles, which causes the sort button to be resized while disappearing.

### Reproducing the problem

See the example code in the [documentation for datatables](https://kivymd.readthedocs.io/en/1.1.1/components/datatables/).

### Screenshots of the problem

kivymd_bug_1441_

### Description of Changes

Removing the lines that resize the button to have a height of zero.

### Code for testing new changes

See the example code in the [documentation for datatables](https://kivymd.readthedocs.io/en/1.1.1/components/datatables/).

### CODE REVIEW

**Comment by nhansendev** [comment]
Note: as far as I know setting the button size to zero serves no purpose as long as setting opacity to zero is sufficient. If there is a situation where opacity leaves something still visible, or the size of the header is affected by the sort button size not being zero, then we would need a different solution. Surely there is a more "proper" way to hide a widget in that case?

**Comment by HeaTTheatR** [comment]
@Obliman In this case, we need to set the button to the disabled/disabled state, because having zero `opacity`, the sort button will still respond to user events.

**Comment by nhansendev** [comment]
Added the button enable/disable lines alongside the opacity ones.

**Comment by HeaTTheatR** [comment]
The PR is deprecated due to the new API of the KivyMD library 2.0.0 version

**Pull request closed without merging**
