### PR TITLE
Added reload method to FitImage class

### PR DESCRIPTION
**Pull request by Neizvestnyj**
Added a standard function for images - `reload`

Function reload image from disk. This facilitates re-loading of images from disk in case the image content changes.
If we change the image to another one with the same name after loading it, we will need to clear the cache, and this will be done by `reload`
```python
from kivymd.app import MDApp
from kivy.lang.builder import Builder

KV = '''
Screen:
    FitImage:
        id: image
        source: 'Image.jpg'
        
    FloatLayout:
        MDIconButton:
            icon: 'reload'
            pos: root.width - self.width, root.height - self.height
            theme_text_color: "Custom"
            text_color: app.theme_cls.primary_color
            on_release: image.container.image.reload()
'''


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(KV)


TestApp().run()

```

https://user-images.githubusercontent.com/40869738/112895474-d88d9500-90e5-11eb-9c99-eb096d0e401a.mov

[kivy image reload](https://kivy.org/doc/stable/api-kivy.uix.image.html?highlight=asyncimage#kivy.uix.image.Image.reload)

### CODE REVIEW

**Comment by podraco** [comment]
I don't see any problem with this, good job.

**Comment by HeaTTheatR** [comment]
> I don't see any problem with this, good job.

I’m not saying that it’s bad. I say that the "Updated FitImage" commit is not informative and should be changed to a more detailed one.

**Comment by podraco** [comment]
how about
`FitImage - reload method added`
also, remember to update it's docs

**Comment by HeaTTheatR** [comment]
> how about
> `FitImage - reload method added`
> also, remember to update it's docs

`Added `reload` method to `FitImage` class`

**Comment by Neizvestnyj** [comment]
@HeaTTheatR Should I create a new commit and then a pull request?

**Comment by HeaTTheatR** [comment]
> @HeaTTheatR Should I create a new commit and then a pull request?

Most likely you should make a new PR.

**Pull request closed without merging**
