### PR TITLE
Fix import error with MDWidget

### PR DESCRIPTION
**Pull request by idorrington92**
Couldn't import the MDWidget from it's current location. 

Running
```
from kivymd.uix.widget import MDWidget
```
raises  
```
ModuleNotFoundError: No module named 'kivymd.uix.widget'
```

Adding it to the uix \_\_init\_\_ caused a circular import error. Instead I made a new submodule and put it in there. Seems to work now.

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@idorrington92 Please read the rules for describing for PR - https://github.com/kivymd/.github/blob/main/.github/pull_request_template.md

**Comment by idorrington92** [comment]
> @idorrington92 Please read the rules for describing for PR - https://github.com/kivymd/.github/blob/main/.github/pull_request_template.md

Hi @HeaTTheatR, I've added some example code. I'm probably being dumb, but can't see how to add screenshot showing this works. I've also tested it with my own app I'm working on and the kitchen sink demo.

**Comment by HeaTTheatR** [comment]
@idorrington92 How should we reproduce the error you describe?

**Comment by idorrington92** [comment]
It's literally just when I try to import MDWidget

```
from kivymd.uix.widget import MDWidget
```

Do you not get an error when you do that?

**Comment by HeaTTheatR** [comment]
I am closing this PR because there is no error in importing the `MDWidget` widget.

**Comment by idorrington92** [comment]
@HeaTTheatR  I just realised this only happens with the install of kivyMD from PyPI. Installing straight from master is fine...

**Pull request closed without merging**
