### PR TITLE
fix elevation behavior when widget has Screen type as parent

### PR DESCRIPTION
**Pull request by mp-007**
possible fix for issue #1327

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@mp-007 There is still a bug for this issue:


https://user-images.githubusercontent.com/16930280/188254721-aa9635b0-f416-42a7-b41f-b93065b3c052.mov

**Comment by mp-007** [comment]
Maybe we can find something in this project: https://github.com/kivy-garden/frostedglass/blob/main/kivy_garden/frostedglass/__init__.py

I think the author was facing the same issues with the shader effect.

**Comment by HeaTTheatR** [comment]
@mp-007 
Yes, it is quite obvious that the problem is in the shader itself. The problem of widgets with elevation behavior in scrollable lists has been solved. But the solution is not quite right. We knew that.

```python
from kivy.lang import Builder

from kivymd.app import MDApp


class Test(MDApp):

    def build(self):
        return Builder.load_string(
            '''
MDScreenManager:

    MDScreen:
        name: "screen 1"

        MDRaisedButton:
            text: "MDRaisedButton"
            pos_hint: {"center_x": .5, "center_y": .5}
            on_release: root.current = "screen 2"

    MDScreen
        name: "screen 2"

        MDRaisedButton:
            text: "MDRaisedButton"
            pos_hint: {"center_x": .5, "center_y": .5}
            on_release: root.current = "screen 3"

    MDScreen
        name: "screen 3"

        MDRaisedButton:
            text: "MDRaisedButton"
            pos_hint: {"center_x": .5, "center_y": .5}
            on_release: root.current = "screen 1"
'''
        )


Test().run()
```

https://user-images.githubusercontent.com/16930280/188297360-36ce3fd8-b855-4a5b-987a-70fb81af41ad.mov


Unfortunately, I don't have too much knowledge on working with shaders.

**Comment by mp-007** [comment]
PR #1336 fix issue #1327

**Pull request closed without merging**
