### PR TITLE
Fix for #772 - set_colors

### LINKED ISSUE #772: Define a courtesy method to set all theme colors
### Description of the Feature

The current process for setting up a palette (unless you are accepting the most basic defaults) gets very long winded and boilerplate-ey with 6 different method calls.

It would be good to create a courtesy method to set them all in one call.

I will submit a PR

### PR DESCRIPTION
**Pull request by runette**
closes #772 

### Description of Changes

Adds a method to `ThemeManager` that allows all of the theme color attributes to be set in one call.

Example and documentation included

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@runette You have not added any documentation that we talked about earlier.

**Comment by runette** [comment]
I think you have different PRs mixed up - we have not discussed anything about this PR before and the method IS documented.

**Comment by runette** [comment]
This is not in any way linked to #755. This is just a courtesy method to avoid you having to make 8 different calls if you need to set all of the theme attributes (i.e. the primary and accent colors with light and dark variants for each one).

**Comment by kulothunganug** [comment]
I think using `**kwargs` will be good.

**Comment by runette** [comment]
Too complicated. If the users want to set the attributes individually then
they can use the existing methods. Adding kwargs here would add as much
boilerplate as using the base methods. This method is just for users who
want to set the entire theme in one set and using positional is much
cleaner: `set_colors("Red', "50","500", "900", "Blue", "50", "500", "900")`
etc

**Pull request merged**
