### PR TITLE
Updated MDDataTable

### PR DESCRIPTION
**Pull request by shashi278**
### Updated existing`MDDataTable` with following features
* `MDDataTable` does not inherit from ModalView class anymore
* Added the feature to use an icon for a row
* Added feature to add sort button for a column
* Added `get_row_checks` method to get list of all checked rows
* Fixed the working of selecting all cells

### Example to test
```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.uix.anchorlayout import AnchorLayout


class Example(MDApp):
    def build(self):
        a = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("No.", dp(30)),
                ("Status", dp(30)),
                ("Signal Name", dp(60)),
                ("Severity", dp(30)),
                ("Stage", dp(30)),
                ("Schedule", dp(30), lambda *args: print("Sorted using Schedule")),
                ("Team Lead", dp(30)),
            ],
            row_data=[
                ("1", ("alert", [255/256,165/256,0,1], "No Signal"), "Astrid: NE shared managed", "Medium", "Triaged", "0:33", "Chase Nguyen"),
                ("2", ("alert-circle", [1,0,0,1], "Offline"), "Cosmo: prod shared ares", "Huge", "Triaged", "0:39", "Brie Furman"),
                ("3", ("checkbox-marked-circle", [39/256, 174/256, 96/256, 1], "Online"), "Phoenix: prod shared lyra-lists", "Minor", "Not Triaged", "3:12", "Jeremy lake"),
                ("4", ("checkbox-marked-circle", [39/256, 174/256, 96/256, 1], "Online"), "Sirius: NW prod shared locations", "Negligible", "Triaged", "13:18", "Angelica Howards"),
                ("5", ("checkbox-marked-circle", [39/256, 174/256, 96/256, 1], "Online"), "Sirius: prod independent account", "Negligible", "Triaged", "22:06", "Diane Okuma"),

            ],
            elevation = 2
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        a.add_widget(self.data_tables)
        return a

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        #show all checked rows data
        print(instance_table.get_row_checks())


Example().run()

```

### Screenshots
test_datatable
ezgif com-resize

#### Note:
* There are still some existing issues with `MDDataTable` mainly because of `RecycleView` which has some issues itself like cloning/changing data.

* Sorting based on a column value should be done by users meaning we don't need to implement a sorting method in `MDDataTable` itself. Users must provide a function that will be called when the sorting button will be pressed. And then they need to give updated data to the `MDDataTable` which will be shown as a result of the sort. However, this feature is not there just yet.

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@shashi278 
Great job!
I'll watch it tomorrow. It's late today and need to sleep.

**Comment by shashi278** [comment]
I'm working on improving selection feedback

**Review by HeaTTheatR — CHANGES_REQUESTED** [review]
We have to check in the `apply_selection method` method which icons belong to this or that column - https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables.py#L350
Otherwise, the icons will be displayed in random order.

**Comment by shashi278** [comment]
> We have to check in the `apply_selection method` method which icons belong to this or that column - https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables.py#L350
> Otherwise, the icons will be displayed in random order.

Yeah, it's fixed now.
ezgif com-optimize

Also, I've updated doc for `MDDataTable` with the updated example

**Pull request merged**
