### PR TITLE
Fixes issue #431

### PR DESCRIPTION
**Pull request by lemousehunter**
### Description of Changes
Fixes menu position issue of MDDropdownMenu on window maximizing and restoring.

### Added Code:
```
Window.bind(on_maximize=self.set_menu_properties)
Window.bind(on_restore=self.set_menu_properties)
```

in `__init__()` method of MDDropDownMenu

### CODE REVIEW

**Comment by lemousehunter** [comment]
@ArtemSBulgakov @HeaTTheatR

**Comment by HeaTTheatR** [comment]
@lemousehunter Why did you remove the documentation from the module?

**Comment by HeaTTheatR** [comment]
@lemousehunter Use `pre-commit` to format your code correctly - https://github.com/kivymd/KivyMD#setup-environmen

**Comment by lemousehunter** [comment]
> 
> 
> @lemousehunter Why did you remove the documentation from the module?

Oops...my bad. I forked it out from the Main Branch and edited the file directly (I only added those 2 lines...I delete anything so I'm not sure what went wrong)

**Comment by HeaTTheatR** [comment]
Re-clone the repository, make changes and create a new pool.

**Pull request closed without merging**
