### PR TITLE
added ability to use icon from md_icons in attr icon of MDExpansionPanel

### PR DESCRIPTION
**Pull request by p0lygun**

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@jakogut 
```python
            if self.icon:
                if self.icon in md_icons.keys():
                    self.panel_cls.add_widget(IconLeftWidget(icon=self.icon))
                else:
                    self.panel_cls.add_widget(ImageLeftWidget(source=self.icon))
            # If the icon is not specified by the user, you must set by default.
            else:
                [...]

            self.add_widget(self.panel_cls)
```
https://github.com/kivymd/KivyMD/pull/457#issuecomment-674187719

**Comment by p0lygun** [comment]
@HeaTTheatR Done

**Review by HeaTTheatR — COMMENTED** [review]
### Right
            if self.icon:
                if self.icon in md_icons.keys():
                    self.panel_cls.add_widget(IconLeftWidget(icon=self.icon, pos_hint={"center_y": .5}))
                else:
                    self.panel_cls.add_widget(ImageLeftWidget(source=self.icon, pos_hint={"center_y": .5}))

### Your version
Снимок экрана 2020-08-15 в 14 43 00

**Comment by p0lygun** [comment]
@HeaTTheatR 
anything else?

**Pull request closed without merging**
