### PR TITLE
added tab_alias to MDTabBase

### PR DESCRIPTION
**Pull request by p0lygun**
### Description of Changes
*  Added a StringProperty (tab_alias) to MDTabBase 
* Useful when you need to differentiate between two MDTabsLabel instances returned by get_tab_list()

Minimal runnable

```py
from kivy.lang import Builder
from kivy.uix.scrollview import ScrollView

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase

KV = """
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs

<Tab>:
    MDList:

        MDBoxLayout:
            adaptive_height: True

            MDFlatButton:
                text: "ADD TAB"
                on_release: app.add_tab()

            MDFlatButton:
                text: "REMOVE LAST TAB"
                on_release: app.remove_tab()

            MDFlatButton:
                text: "GET TAB LIST"
                on_release: app.get_tab_list()
<TypeTab>
    id : type_tab
    MDList:

        MDBoxLayout:
            adaptive_height: True

            MDFlatButton:
                text: "ADD TAB"
                on_release: app.add_tab()

            MDFlatButton:
                text: "REMOVE LAST TAB"
                on_release: app.remove_tab()

            MDFlatButton:
                text: "GET TAB LIST"
                on_release: app.get_tab_list()
"""


class Tab(ScrollView, MDTabsBase):
    """Class implementing content for a tab."""


class TypeTab(ScrollView, MDTabsBase):
    """Class implementing content for a tab."""


class Example(MDApp):
    index = 0

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.add_tab()

    def get_tab_list(self):
        """Prints a list of tab objects."""

        print(self.root.ids.android_tabs.get_tab_list())

        for i in self.root.ids.android_tabs.get_tab_list():
            print(f"tab_alias is {i.tab_alias}")

    def add_tab(self):
        self.index += 1
        self.root.ids.android_tabs.add_widget(
            TypeTab(text=f"{self.index} tab", tab_alias=f"{self.index}")
        )

    def remove_tab(self):
        self.index -= 1
        self.root.ids.android_tabs.remove_widget(
            self.root.ids.android_tabs.get_tab_list()[0]
        )


Example().run()

```

image

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@gala0sup Thanks for trying to contribute to the library. But I'm not sure how helpful these changes are. Two objects in Python will always be different from each other.

**Comment by p0lygun** [comment]
@HeaTTheatR 
i don't agree 
because with this u can have two names for each tab 
one for showing and one for accessing 
like I have a tab with name "Some name"
and I wanted to add an item which has an attribute say "type_1"
now if a wanted to add the item to the tab I would need to something like 

```py
tabs_list = app.root.ids.tabs_.get_tab_list()
for tab in tabs_list:
    if tab.text == "Some name":
        tab.add_widget(item)
```
but if we use tab_alias

```
tabs_list = app.root.ids.tabs_.get_tab_list()
for tab in tabs_list:
    if tab.tab_alias == item.type:
        tab.add_widget(item)
```
it makes it much easier to add widgets to a tab

**Comment by HeaTTheatR** [comment]
@gala0sup I don't see any practical profit in specifying the name of the tab (`tab_alias`) to which I want to add something when initializing the `MDTabs` class. The following code is more logical:

```python
for tab in tabs_list:
    if tab.text == "Some name":
        tab.add_widget(item)
```

**Comment by HeaTTheatR** [comment]
@gala0sup If you have any other ideas on how to improve the library, or if you are fixing a bug in the library, feel free to create another pull request.

**Comment by ArtemSBulgakov** [comment]
@gala0sup Users always make their own classes for tabs. 
```python
class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''
```
So you can just add your properties
```python
class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''
	tab_alias = StringProperty()
```

**Pull request closed without merging**
