### PR TITLE
Closing animation for bottomsheet

### PR DESCRIPTION
**Pull request by shashi278**
Incorporated feature request in #745

### Screenshots
ezgif com-video-to-gif(6)

### CODE REVIEW

**Comment by HeaTTheatR** [comment]
@shashi278 These changes don't work. Because the on_dismiss method is called after the modal window is closed.

**Comment by HeaTTheatR** [comment]
@shashi278 I've already fixed that.

**Comment by shashi278** [comment]
It seemed to be working though. Did I miss something? 🤔

**Comment by shashi278** [comment]
Should it be done inside `on_pre_dismiss`? @HeaTTheatR

**Comment by HeaTTheatR** [comment]
@shashi278 No. We had to completely rewrite the dismiss method:

```python
    def dismiss(self, *args, **kwargs):
        def dismiss(*args):
            self.dispatch("on_pre_dismiss")
            self._gl_content.clear_widgets()
            self._real_remove_widget()
            self.dispatch("on_dismiss")

        if self.animation:
            a = Animation(height=0, d=self.duration_closing)
            a.bind(on_complete=dismiss)
            a.start(self._gl_content)
        else:
            dismiss()```

**Comment by shashi278** [comment]
I see. Glad you already fixed that! 😅

**Pull request merged**
