### PR TITLE
Standard and modal types for navigation drawer

### PR DESCRIPTION
**Pull request by wasimafser**
### Description of Changes
* Add type attribute to NavigationLayout to account for 'standard' and 'modal' navigation types
* with reference to #436 

### Screenshots
Screenshot 2020-08-04 at 7 37 51 PM
Screenshot 2020-08-04 at 7 37 02 PM

### CODE REVIEW

**Comment by ArtemSBulgakov** [comment]
I think we could just make MDNavigationDrawer always opened and set position with size to ScreenManager instead of using additional BoxLayout. Also it should have feature to be closed by button.

[Standard Navigation Drawer](https://material.io/components/navigation-drawer#standard-drawer)

**Comment by wasimafser** [comment]
> I think we could just make MDNavigationDrawer always opened and set position with size to ScreenManager instead of using additional BoxLayout. Also it should have feature to be closed by button.

Do you mean to have it the same as in the picture ? with a toolbar above the whole layout ?

I pictured this one :
image

**Comment by ArtemSBulgakov** [comment]
Position of toolbar is not important. I am saying about way to close drawer (it may be necessary for some apps) and implementation (using Navigation Layout without BoxLayout inside it).

**Comment by wasimafser** [comment]
@ArtemSBulgakov , please check now and let me know ! we can use the existing set_state to open / close / toggle

**Comment by ArtemSBulgakov** [comment]
@wasimafser Please don't forget to run pre-commit before committing. See Readme for instructions. Also fix flake8 warnings

**Comment by wasimafser** [comment]
> @wasimafser Please don't forget to run pre-commit before committing. See Readme for instructions. Also fix flake8 warnings

done ! thank you for letting me know

**Comment by ArtemSBulgakov** [comment]
Made some changes to allow changing anchor and type when drawer is opened. Also moved `type` to MDNavigationDrawer and added `enable_swiping` property.

**Comment by wasimafser** [comment]
> Made some changes to allow changing anchor and type when drawer is opened. Also moved `type` to MDNavigationDrawer and added `enable_swiping` property.

Saw your changes, that's great !

**Pull request merged**
