### PR TITLE
Fixed issues with indicator_type

### PR DESCRIPTION
**Pull request by shashi278**
Fixed issues with `tab_indicator_type` as mentioned in #697

### CODE REVIEW

**Comment by shashi278** [comment]
This is a better fix without involving clocks. I'd suggest you to merge this.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/commit/f5ceaa0f34097817cf65ed858a1a234ac7195331

**Comment by shashi278** [comment]
> [f5ceaa0](https://github.com/kivymd/KivyMD/commit/f5ceaa0f34097817cf65ed858a1a234ac7195331)

I saw those changes that's why I said this one is better because it doesn't assume 2 sec delay in displaying indicator

**Comment by HeaTTheatR** [comment]
@shashi278 Your changes will contain errors. When resizing the window ... Not required `_trigger_update_tab_indicator `method ... and so on

**Comment by shashi278** [comment]
But this method was already there. I didn't introduce it. All I'm saying is, if we're talking about the indicator then we should not make it available using Clock. Plus, if there's any function we don't need anymore, we can simply remove it.

**Comment by HeaTTheatR** [comment]
@shashi278 Try to pull requests with my changes and then add your own if you think my changes are not very good.

**Pull request closed without merging**
