### PR TITLE
Updated stackoverflow shield in README.md

### PR DESCRIPTION
**Pull request by p0lygun**
### Description of Changes
* ...Changed shield link so now it does not show invalid

### CODE REVIEW

**Comment by ArtemSBulgakov** [comment]
It usually shows count of questions with tag kivymd. But sometimes shields not working properly and it shows "invalid"

**Comment by p0lygun** [comment]
i have never seen it showing  number of questions 
i have always seen it to be Invalid

**Comment by ArtemSBulgakov** [comment]
Found this: https://github.com/badges/shields/issues/3591

**Comment by p0lygun** [comment]
well then I guess I'll close this pull request

**Pull request closed without merging**
